package sn.ondmoney.notificationservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationRequestAllPropertiesEquals(NotificationRequest expected, NotificationRequest actual) {
        assertNotificationRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationRequestAllUpdatablePropertiesEquals(NotificationRequest expected, NotificationRequest actual) {
        assertNotificationRequestUpdatableFieldsEquals(expected, actual);
        assertNotificationRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationRequestAutoGeneratedPropertiesEquals(NotificationRequest expected, NotificationRequest actual) {
        assertThat(actual)
            .as("Verify NotificationRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationRequestUpdatableFieldsEquals(NotificationRequest expected, NotificationRequest actual) {
        assertThat(actual)
            .as("Verify NotificationRequest relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getAccountNumber()).as("check accountNumber").isEqualTo(expected.getAccountNumber()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getChannels()).as("check channels").isEqualTo(expected.getChannels()))
            .satisfies(a -> assertThat(a.getData()).as("check data").isEqualTo(expected.getData()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getImmediate()).as("check immediate").isEqualTo(expected.getImmediate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationRequestUpdatableRelationshipsEquals(NotificationRequest expected, NotificationRequest actual) {
        // empty method
    }
}
