package sn.ondmoney.notificationservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationPreferenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPreferenceAllPropertiesEquals(NotificationPreference expected, NotificationPreference actual) {
        assertNotificationPreferenceAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationPreferenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPreferenceAllUpdatablePropertiesEquals(
        NotificationPreference expected,
        NotificationPreference actual
    ) {
        assertNotificationPreferenceUpdatableFieldsEquals(expected, actual);
        assertNotificationPreferenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPreferenceAutoGeneratedPropertiesEquals(
        NotificationPreference expected,
        NotificationPreference actual
    ) {
        assertThat(actual)
            .as("Verify NotificationPreference auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPreferenceUpdatableFieldsEquals(NotificationPreference expected, NotificationPreference actual) {
        assertThat(actual)
            .as("Verify NotificationPreference relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getSmsEnabled()).as("check smsEnabled").isEqualTo(expected.getSmsEnabled()))
            .satisfies(a -> assertThat(a.getEmailEnabled()).as("check emailEnabled").isEqualTo(expected.getEmailEnabled()))
            .satisfies(a -> assertThat(a.getPushEnabled()).as("check pushEnabled").isEqualTo(expected.getPushEnabled()))
            .satisfies(a -> assertThat(a.getMutedTypes()).as("check mutedTypes").isEqualTo(expected.getMutedTypes()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationPreferenceUpdatableRelationshipsEquals(
        NotificationPreference expected,
        NotificationPreference actual
    ) {
        // empty method
    }
}
