package sn.ondmoney.notificationservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationLogAllPropertiesEquals(NotificationLog expected, NotificationLog actual) {
        assertNotificationLogAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationLogAllUpdatablePropertiesEquals(NotificationLog expected, NotificationLog actual) {
        assertNotificationLogUpdatableFieldsEquals(expected, actual);
        assertNotificationLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationLogAutoGeneratedPropertiesEquals(NotificationLog expected, NotificationLog actual) {
        assertThat(actual)
            .as("Verify NotificationLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationLogUpdatableFieldsEquals(NotificationLog expected, NotificationLog actual) {
        assertThat(actual)
            .as("Verify NotificationLog relevant properties")
            .satisfies(a -> assertThat(a.getNotificationId()).as("check notificationId").isEqualTo(expected.getNotificationId()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getChannel()).as("check channel").isEqualTo(expected.getChannel()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getRecipient()).as("check recipient").isEqualTo(expected.getRecipient()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()))
            .satisfies(a -> assertThat(a.getSentAt()).as("check sentAt").isEqualTo(expected.getSentAt()))
            .satisfies(a -> assertThat(a.getRetryCount()).as("check retryCount").isEqualTo(expected.getRetryCount()))
            .satisfies(a -> assertThat(a.getChannelResults()).as("check channelResults").isEqualTo(expected.getChannelResults()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationLogUpdatableRelationshipsEquals(NotificationLog expected, NotificationLog actual) {
        assertThat(actual)
            .as("Verify NotificationLog relationships")
            .satisfies(a -> assertThat(a.getNotification()).as("check notification").isEqualTo(expected.getNotification()));
    }
}
