package sn.ondmoney.notificationservice.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.ondmoney.notificationservice.domain.AssertUtils.bigDecimalCompareTo;

public class TransactionEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionEventAllPropertiesEquals(TransactionEvent expected, TransactionEvent actual) {
        assertTransactionEventAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionEventAllUpdatablePropertiesEquals(TransactionEvent expected, TransactionEvent actual) {
        assertTransactionEventUpdatableFieldsEquals(expected, actual);
        assertTransactionEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionEventAutoGeneratedPropertiesEquals(TransactionEvent expected, TransactionEvent actual) {
        assertThat(actual)
            .as("Verify TransactionEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionEventUpdatableFieldsEquals(TransactionEvent expected, TransactionEvent actual) {
        assertThat(actual)
            .as("Verify TransactionEvent relevant properties")
            .satisfies(a -> assertThat(a.getTransactionId()).as("check transactionId").isEqualTo(expected.getTransactionId()))
            .satisfies(a -> assertThat(a.getSenderAccount()).as("check senderAccount").isEqualTo(expected.getSenderAccount()))
            .satisfies(a -> assertThat(a.getReceiverAccount()).as("check receiverAccount").isEqualTo(expected.getReceiverAccount()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()))
            .satisfies(a -> assertThat(a.getAdditionalData()).as("check additionalData").isEqualTo(expected.getAdditionalData()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionEventUpdatableRelationshipsEquals(TransactionEvent expected, TransactionEvent actual) {
        // empty method
    }
}
