package sn.ondmoney.notification.domain.enumeration;

/**
 * Les types d'événements de notification supportés par le système Ond Money.
 * Catégorisé par type de microservice (AUTH, TXE, AIRTIME, etc.).
 */
public enum NotificationType {
    OTP_REQUEST,
    EMAIL_VERIFICATION_REQUEST,
    PIN_RESET_REQUEST,
    ACCOUNT_CREATED,
    KYC_REQUIRED_ALERT,
    PIN_RESET_CONFIRM,
    SECURITY_ALERT_LOGIN,
    ACCOUNT_BLOCKED,
    TRANSFER_COMPLETED,
    TRANSFER_FAILED_FUNDS,
    TRANSFER_FAILED_BLOCKED,
    TRANSFER_FAILED_CONCURRENCY,
    AIRTIME_COMPLETED,
    AIRTIME_FAILED_FUNDS,
    AIRTIME_FAILED_BLOCKED,
    BILL_PAYMENT_COMPLETED,
    BILL_PAYMENT_FAILED_FUNDS,
    BILL_PAYMENT_FAILED_PAYEE,
    MERCHANT_PAYMENT_COMPLETED,
    MERCHANT_PAYMENT_FAILED_FUNDS,
    MERCHANT_PAYMENT_FAILED_PAYEE,
    MERCHANT_PAYMENT_CLIENT_BLOCKED,
    MERCHANT_PAYMENT_BUSINESS_BLOCKED,
    BANK2WALLET_COMPLETED,
    WALLET2BANK_COMPLETED,
    BANK2WALLET_FAILED_FUNDS,
    WALLET2BANK_FAILED_FUNDS,
    BANK2WALLET_FAILED_OND_BLOCKED,
    WALLET2BANK_FAILED_OND_BLOCKED,
    BANK2WALLET_FAILED_BANK_BLOCKED,
    WALLET2BANK_FAILED_BANK_BLOCKED,
}
