package sn.ondmoney.notification.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationTemplateAllPropertiesEquals(NotificationTemplate expected, NotificationTemplate actual) {
        assertNotificationTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationTemplateAllUpdatablePropertiesEquals(NotificationTemplate expected, NotificationTemplate actual) {
        assertNotificationTemplateUpdatableFieldsEquals(expected, actual);
        assertNotificationTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationTemplateAutoGeneratedPropertiesEquals(NotificationTemplate expected, NotificationTemplate actual) {
        assertThat(actual)
            .as("Verify NotificationTemplate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationTemplateUpdatableFieldsEquals(NotificationTemplate expected, NotificationTemplate actual) {
        assertThat(actual)
            .as("Verify NotificationTemplate relevant properties")
            .satisfies(a -> assertThat(a.getTemplateCode()).as("check templateCode").isEqualTo(expected.getTemplateCode()))
            .satisfies(a ->
                assertThat(a.getNotificationChannel()).as("check notificationChannel").isEqualTo(expected.getNotificationChannel())
            )
            .satisfies(a ->
                assertThat(a.getNotificationLanguage()).as("check notificationLanguage").isEqualTo(expected.getNotificationLanguage())
            )
            .satisfies(a -> assertThat(a.getNotificationType()).as("check notificationType").isEqualTo(expected.getNotificationType()))
            .satisfies(a ->
                assertThat(a.getNotificationTemplateType())
                    .as("check notificationTemplateType")
                    .isEqualTo(expected.getNotificationTemplateType())
            )
            .satisfies(a -> assertThat(a.getSubjectTemplate()).as("check subjectTemplate").isEqualTo(expected.getSubjectTemplate()))
            .satisfies(a -> assertThat(a.getBodyTemplate()).as("check bodyTemplate").isEqualTo(expected.getBodyTemplate()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationTemplateUpdatableRelationshipsEquals(NotificationTemplate expected, NotificationTemplate actual) {
        // empty method
    }
}
